#!/bin/sh
# Create or refresh the project's Python virtual environment.
#
# Idempotent: safe to run on a fresh clone, after a git pull, or repeatedly.
# The self-update phase calls it whenever a pull touched pyproject.toml,
# requirements.txt or the C++ sources, so it must stay quick when there is
# nothing to do.
#
#   ./bootstrap.sh              # venv + runtime and dev dependencies
#   MU2EDAQ_PYTHON=python3.9 ./bootstrap.sh
#   ./bootstrap.sh --with-cpp   # also configure and build libmu2eprobe
#
# Works on Linux and macOS.  Windows uses bootstrap.ps1.

set -eu

PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$PROJECT_DIR"

VENV_DIR="${VENV_DIR:-$PROJECT_DIR/venv}"
PYTHON="${MU2EDAQ_PYTHON:-python3}"
WITH_CPP=0

for arg in "$@"; do
  case "$arg" in
    --with-cpp) WITH_CPP=1 ;;
    -h|--help)
      sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "bootstrap.sh: unknown option $arg" >&2; exit 2 ;;
  esac
done

if ! command -v "$PYTHON" >/dev/null 2>&1; then
  echo "error: $PYTHON not found. Set MU2EDAQ_PYTHON to your interpreter." >&2
  exit 1
fi

# The DAQ nodes run whatever the site python3 is; 3.9 is the floor.
"$PYTHON" - <<'PYEOF' || exit 1
import sys
if sys.version_info < (3, 9):
    sys.stderr.write(
        f"error: Python 3.9 or newer is required, found {sys.version.split()[0]}\n")
    raise SystemExit(1)
PYEOF

if [ ! -d "$VENV_DIR" ]; then
  echo "==> creating the virtual environment in $VENV_DIR"
  "$PYTHON" -m venv "$VENV_DIR"
else
  echo "==> reusing the existing virtual environment in $VENV_DIR"
fi

VENV_PY="$VENV_DIR/bin/python"
echo "==> upgrading pip"
"$VENV_PY" -m pip install --quiet --upgrade pip setuptools wheel

echo "==> installing mu2edaq-power-recovery and its dependencies"
# Editable, so a git pull takes effect without a reinstall -- which is what
# makes the self-update phase's rebuild cheap.
"$VENV_PY" -m pip install --quiet --editable ".[dev]"

# Regenerate requirements.txt from what was actually resolved, so the file
# always matches a working installation rather than drifting from it.
if [ -w "$PROJECT_DIR/requirements.txt" ] || [ ! -e "$PROJECT_DIR/requirements.txt" ]; then
  {
    echo "# Generated by bootstrap.sh -- the resolved runtime dependency set."
    echo "# Edit pyproject.toml, not this file; re-run ./bootstrap.sh to refresh."
    "$VENV_PY" -m pip freeze --exclude-editable 2>/dev/null \
      | grep -Ev '^(pip|setuptools|wheel)==' || true
  } > "$PROJECT_DIR/requirements.txt.new"
  mv "$PROJECT_DIR/requirements.txt.new" "$PROJECT_DIR/requirements.txt"
fi

mkdir -p "$PROJECT_DIR/logs" "$PROJECT_DIR/data" "$PROJECT_DIR/html" "$PROJECT_DIR/core"

if [ "$WITH_CPP" -eq 1 ]; then
  if command -v cmake >/dev/null 2>&1; then
    echo "==> building the optional C/C++ probe library"
    cmake -S "$PROJECT_DIR" -B "$PROJECT_DIR/build" \
          -DCMAKE_BUILD_TYPE=Release -DBOOTSTRAP_VENV=OFF >/dev/null
    cmake --build "$PROJECT_DIR/build" --parallel
  else
    echo "    cmake not found; skipping the C++ library."
    echo "    The pure-Python reachability fallback will be used."
  fi
fi

if [ ! -f "$PROJECT_DIR/config/.env" ] && [ -f "$PROJECT_DIR/config/.env.example" ]; then
  echo "==> note: config/.env does not exist."
  echo "    Copy config/.env.example to config/.env to set local overrides."
fi

echo
echo "Bootstrap complete."
echo "  activate :  . $VENV_DIR/bin/activate"
echo "  rehearse :  mu2e-power-recovery --phase all --simulate"
echo "  survey   :  mu2e-power-state"
