#!/usr/bin/env python3
"""Regenerate the generated parts of the man pages and check the rest for drift.

The check reference in mu2edaq-power-recovery(7) is a transcription of the live
check registry.  Transcriptions rot: a check added to
:mod:`mu2edaq_power_recovery.checks` is registered, selectable in checks.yaml
and reported on, and nothing forces anyone to mention it in the manual.  The
table was in fact first produced by a throwaway script that was not kept, so
there was no way to tell whether the page still matched the code.  This script
is that script, kept, and wired into the build and the test suite.

Four things are verified, and one of them is repaired:

  1. the CHECK REFERENCE section of man/man7/mu2edaq-power-recovery.7 against
     REGISTRY / DESCRIPTIONS / NEEDS_ROOT  -- repaired by --write;
  2. every console script declared in pyproject.toml has a man/man1 page;
  3. every configuration key in settings.DEFAULTS has each component of its
     dotted path named inside the .SS section for its *top-level* segment
     (see check_config_keys for what this does and does not guarantee);
  4. every man page renders without a groff warning.

Items 2-4 are reported, never repaired: a missing page or an undocumented
setting needs prose that only a human can write.

Know the limits before quoting a passing run as a guarantee:

  * Check 2 iterates [project.scripts], so a tool under tools/ -- this script
    included -- cannot be caught by it.  man/man1/mu2edaq-generate-docs.1 is
    this script's page and exists because of that gap.
  * Nothing here compares prose against behaviour.  A man page can describe a
    safety gate the code does not implement and pass all four checks.
  * Markdown is not examined at all: README.md, CLAUDE.md, PROJECT-STATUS.md
    and docs/ are outside every check.

The generated block is delimited by troff comments so the surrounding prose
stays hand-written:

    .\\" BEGIN GENERATED CHECK REFERENCE
    ...
    .\\" END GENERATED CHECK REFERENCE

The table is emitted as .TP entries rather than a tbl table on purpose: tbl
needs a preprocessor pass, and a page containing an unpreprocessed .TS block
renders as garbage under plain `groff -man`, which is how these pages are read
during a recovery.

Usage::

    ./venv/bin/python tools/generate-docs.py --check    # report drift, change nothing
    ./venv/bin/python tools/generate-docs.py --write    # regenerate in place
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Set, Tuple

ROOT = Path(__file__).resolve().parent.parent

BEGIN_MARKER = '.\\" BEGIN GENERATED CHECK REFERENCE'
END_MARKER = '.\\" END GENERATED CHECK REFERENCE'

#: Page holding the generated check reference.
OVERVIEW_PAGE = Path("man/man7/mu2edaq-power-recovery.7")

#: Font macros whose arguments name a thing rather than describe it.  A key is
#: considered documented when it appears as an argument to one of these inside
#: the .SS section named by the key's top-level segment.
NAME_MACROS = {"B", "I", "BR", "RB", "BI", "IB", "IR", "RI"}

_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


# ---------------------------------------------------------------------------
# 1. check reference
# ---------------------------------------------------------------------------

def importable(root: Path) -> None:
    """Make the package importable from *root* without installing it."""
    source = str(root / "src")
    if source not in sys.path:
        sys.path.insert(0, source)


def load_registry(root: Path) -> List[Tuple[str, str, bool]]:
    """(check id, description, needs root) for every registered check.

    Imported rather than parsed: the registry is populated by decorators at
    import time, so importing the package is the only way to see what is
    actually registered, including checks added to a module the man page has
    never heard of.
    """
    importable(root)
    from mu2edaq_power_recovery import checks  # noqa: E402

    return [(cid, checks.DESCRIPTIONS.get(cid, ""), cid in checks.NEEDS_ROOT)
            for cid in sorted(checks.REGISTRY)]


def troff_escape(text: str) -> str:
    """Make *text* safe as a troff input line.

    A backslash is an escape introducer, and a line whose first character is
    '.' or "'" is read as a macro call, so a description starting with either
    would silently vanish from the page.
    """
    text = text.replace("\\", "\\e")
    if text[:1] in (".", "'"):
        text = "\\&" + text
    return text


def render_check_reference(entries: Iterable[Tuple[str, str, bool]]) -> str:
    lines = [BEGIN_MARKER,
             '.\\" Generated by tools/generate-docs.py -- do not edit by hand.']
    for check_id, description, needs_root in entries:
        lines.append(".TP")
        lines.append(".B " + check_id + (" [root]" if needs_root else ""))
        lines.append(troff_escape(description))
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def splice(page_text: str, block: str, page: Path) -> str:
    """Replace the delimited block in *page_text* with *block*."""
    start = page_text.find(BEGIN_MARKER)
    end = page_text.find(END_MARKER)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(
            f"{page}: the generated block markers are missing or out of order.\n"
            f"  Expected a region delimited by\n"
            f"    {BEGIN_MARKER}\n"
            f"    {END_MARKER}")
    end += len(END_MARKER)
    # Swallow the newline that terminates the end marker; *block* supplies it.
    if page_text[end:end + 1] == "\n":
        end += 1
    return page_text[:start] + block + page_text[end:]


def check_reference(root: Path, write: bool) -> List[str]:
    page = root / OVERVIEW_PAGE
    if not page.exists():
        return [f"missing page: {OVERVIEW_PAGE}"]

    current = page.read_text()
    updated = splice(current, render_check_reference(load_registry(root)), page)
    if updated == current:
        return []
    if write:
        page.write_text(updated)
        return []
    return [f"{OVERVIEW_PAGE}: CHECK REFERENCE does not match the live registry "
            f"-- run tools/generate-docs.py --write"]


# ---------------------------------------------------------------------------
# 2. console scripts
# ---------------------------------------------------------------------------

def console_scripts(root: Path) -> List[str]:
    """Names declared under [project.scripts] in pyproject.toml.

    tomllib is stdlib from 3.11 only and this project supports 3.9, so the
    section is read line by line when it is absent.  The fallback is adequate
    because the section is a flat table of ``name = "target"`` lines.
    """
    text = (root / "pyproject.toml").read_text()
    try:
        import tomllib
    except ImportError:
        names = []
        in_section = False
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("["):
                in_section = stripped == "[project.scripts]"
                continue
            if in_section and "=" in stripped and not stripped.startswith("#"):
                names.append(stripped.split("=", 1)[0].strip())
        return sorted(names)
    return sorted(tomllib.loads(text).get("project", {}).get("scripts", {}))


def check_man1_pages(root: Path) -> List[str]:
    problems = []
    for name in console_scripts(root):
        page = Path("man/man1") / f"{name}.1"
        if not (root / page).exists():
            problems.append(f"console script {name} has no {page}")
    return problems


# ---------------------------------------------------------------------------
# 3. configuration keys
# ---------------------------------------------------------------------------

def default_keys(root: Path) -> List[str]:
    importable(root)
    from mu2edaq_power_recovery.settings import DEFAULTS  # noqa: E402

    def walk(mapping, prefix=""):
        for key, value in mapping.items():
            path = f"{prefix}.{key}" if prefix else key
            if isinstance(value, dict):
                yield from walk(value, path)
            else:
                yield path

    return list(walk(DEFAULTS))


def macro_arguments(line: str) -> List[str]:
    """Arguments of a troff font macro, with quoting resolved.

    ``.IR addr ", " kv_mount`` is three arguments, the middle one a literal
    separator; naive whitespace splitting would lose the quoted forms that the
    man pages use to list sibling keys on one line.
    """
    parts = line[1:].split(None, 1)
    if not parts or parts[0] not in NAME_MACROS:
        return []
    rest = parts[1] if len(parts) > 1 else ""
    return [quoted or bare
            for quoted, bare in re.findall(r'"([^"]*)"|(\S+)', rest)]


def documented_names(page_text: str) -> Dict[str, Set[str]]:
    """Map each .SS section of a man5 page to the identifiers it names."""
    sections: Dict[str, Set[str]] = {}
    current: Set[str] = set()
    for line in page_text.splitlines():
        if line.startswith(".SS "):
            name = line[4:].strip().strip('"')
            current = sections.setdefault(name, set())
        elif line.startswith(".SH "):
            current = set()
        elif line.startswith("."):
            for argument in macro_arguments(line):
                current.update(_IDENT.findall(argument))
    return sections


def check_config_keys(root: Path) -> List[str]:
    """Every DEFAULTS key is named in the man5 section for its top segment.

    This is section-scoped *identifier* matching, not dotted-path matching, and
    the distinction matters when quoting the result.  ``vault.addr`` is split at
    the first dot; the ``.SS vault`` section is searched for the identifier
    ``addr`` as a font-macro argument.  The pages are written that way on
    purpose -- ``.SS vault`` then ``.B addr``, rather than repeating the full
    path on every entry -- so only 12 of the 77 keys have their complete dotted
    path written out verbatim anywhere in man/man5.

    The consequence is that a leaf documented under the wrong parent is not
    caught, and a leaf whose name collides with an unrelated identifier named in
    the same section would pass without being documented.  Checked by hand
    against the current pages, no such false pass exists.  What a clean run
    guarantees is "every key's name appears in the right section", not "every
    key is documented".
    """
    sections: Dict[str, Set[str]] = {}
    for page in sorted((root / "man" / "man5").glob("*.5")):
        for name, names in documented_names(page.read_text()).items():
            sections.setdefault(name, set()).update(names)

    problems = []
    for key in default_keys(root):
        section, _, remainder = key.partition(".")
        known = sections.get(section)
        if known is None:
            problems.append(f"config key {key}: no .SS {section} in any man5 page")
            continue
        missing = [part for part in remainder.split(".") if part not in known]
        if missing:
            problems.append(
                f"config key {key}: {', '.join(missing)} not named under "
                f".SS {section} in any man5 page")
    return problems


# ---------------------------------------------------------------------------
# 4. groff
# ---------------------------------------------------------------------------

def man_pages(root: Path) -> List[Path]:
    return sorted(p for p in (root / "man").rglob("*")
                  if p.is_file() and re.fullmatch(r"\.[1-8]", p.suffix))


def lint_man_pages(root: Path, quiet: bool) -> List[str]:
    """Render every page and treat any groff diagnostic as a failure.

    A groff warning is not cosmetic here: the usual causes -- an unescaped
    leading '.' inside an .EX block, an unknown macro, an unterminated font
    change -- silently drop or mangle the text an operator is reading in the
    middle of an outage.
    """
    if shutil.which("groff") is None:
        if not quiet:
            print("note: groff not found -- man pages were not rendered")
        return []

    problems = []
    for page in man_pages(root):
        completed = subprocess.run(
            ["groff", "-man", "-Tascii", "-ww", str(page)],
            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
        relative = page.relative_to(root)
        # groff reports "troff:<absolute path>:<line>: warning: ...".  Trading
        # the absolute path for the relative one keeps the report readable and
        # the same on every machine.
        noise = f"troff:{page}:"
        for line in completed.stderr.splitlines():
            line = line.strip()
            if not line:
                continue
            if line.startswith(noise):
                problems.append(f"{relative}:{line[len(noise):]}")
            else:
                problems.append(f"{relative}: {line}")
        if completed.returncode != 0 and not completed.stderr.strip():
            problems.append(f"{relative}: groff exited {completed.returncode}")
    return problems


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate-docs.py",
        description="Regenerate the generated man page sections and check the "
                    "documentation against the code.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                      help="report drift and exit non-zero; change nothing "
                           "(the default)")
    mode.add_argument("--write", action="store_true",
                      help="regenerate the generated sections in place")
    parser.add_argument("--root", type=Path, default=ROOT,
                        help="project root (default: the tree this script is in)")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="print nothing on success")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    problems = []
    problems += check_reference(root, write=args.write)
    problems += check_man1_pages(root)
    problems += check_config_keys(root)
    problems += lint_man_pages(root, quiet=args.quiet)

    if problems:
        print(f"{len(problems)} documentation problem(s):", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    if not args.quiet:
        verb = "regenerated" if args.write else "checked"
        print(f"documentation {verb}: {len(man_pages(root))} man pages, "
              f"{len(console_scripts(root))} console scripts, "
              f"{len(default_keys(root))} configuration keys")
    return 0


if __name__ == "__main__":
    sys.exit(main())
